var
  Scores, Barracks, SpawnX, SpawnY, RescueTileX, RescueTileY, RescuesCount, RescuesDelay, RescueArmy, RescueRecruits, Direction: array[0..3] of Integer;
  RescueColor: array[0..3] of ANSIString;
  RescueSquadPositionX, RescueSquadPositionY, RescueSquadFormation: array[0..3] of array[0..4] of Integer;
  I, K, Wave, General, WaveTime, AIBarracks, AIGroup: Integer;
  Unlocked: array[0..3] of array[15..23] of Boolean;
  bImmediateKill, bDouble, bNewConscription, 
  bReinforce, bReborn, bNewborn, Check, bMsg, bRescueMsg, bRanged: Boolean;
  RallyPointX, RallyPointY, AttackPointX, AttackPointY: array[4..7] of Integer;
  AISpawnX, AISpawnY: array[0..2] of array[4..7] of Integer;


const
  MAX_WAVE = 30;                       //Maximum number of AI waves. For now, 30 waves implemented
  BONUS_WAVE = 18;                     //Players get a random bonus with 18th wave
  BONUS_CHANCE = 0.1375;               //13,75% chance to activate some bonuses
  KILL_CHANCE = 0.125;                 //12,5% chance to activate Immediate Kill bonus
  DOUBLE_CHANCE = 0.15;                //15% chance to activate Double bonus
  REBORN_CHANCE = 0.15;                //15% chance to activate Reborn bonus
  NEWBORN_CHANCE = 0.125;              //12,5% chance to activate Newborn Ally  bonus
  RANGED_CHANCE = 0.175;               //17,5% chance to activate Ranged bonus
  MAX_ARMY_COUNT = 120;                //Maximum army count to activate extra recruits bonus
  RESCUE_RECRUITS_COUNT = 10;          //Maximum recruits count for rescue squad bonus
  RESCUE_ARMY_COUNT = 110;             //Player should have no more than 110 soldiers to use rescue squad bonus
  RESCUE_DELAY = 2400;                 //4 minutes delay
  RESCUES_PER_PLAYER = 3;              //Player can use bonus 3 times
  RESCUE_WAVE = 26;                    //Bonus available since 26th wave
  MAX_RANGED = 120;                    //Maximum ranged count per player
  DEBUG_MODE = False;                  //Debug option, to see how script works


procedure AutoFeed;
var
  UnitsToFeed: array of Integer;
begin
  for I := 0 to 8 do
  begin
    if States.PlayerEnabled(I) then
      UnitsToFeed := States.PlayerGetAllUnits(I);
    for K := 0 to length(UnitsToFeed) - 1 do
      Actions.UnitHungerSet(UnitsToFeed[K], States.UnitMaxHunger);
  end;
end;


procedure CheckDebugBonus;
begin
  if Wave = 18 then
    bImmediateKill := True;

  if Wave = 20 then
  begin
    bImmediateKill := False;
    bDouble := True;
  end;

  if Wave = 22 then
  begin
    bDouble := False;
    bNewConscription := True;
  end;

  if Wave = 24 then
  begin
    bNewConscription := False;
    bReinforce := True;
  end;

  if Wave = 26 then
  begin
    bReinforce := False;
    bReborn := True;
  end;

  if Wave = 28 then
  begin
    bReborn := False;
    bNewborn := True;
  end;
end;


procedure CheckIdleGroups;
var
  Groups: array of Integer;
begin
  for K := 4 to 7 do
  begin
    Groups := States.PlayerGetAllGroups(K);
  for I := 0 to length(Groups) - 1 do
    if States.GroupIdle(Groups[I]) then
      Actions.GroupOrderWalk(Groups[I], AttackPointX[States.GroupOwner(Groups[I])], AttackPointY[States.GroupOwner(Groups[I])], States.KaMRandomI(8));
  end;
end;


function DebugHeader: ANSIString;
begin
  Result := 'WARNING! DEBUG MODE IS ON!';

  if not DEBUG_MODE then
    Result := ''

  else
  begin

    if bImmediateKill then
      Result := 'DEBUG MODE ON! You now test bonus: Immediate Kill|';

    if bDouble then
      Result := 'DEBUG MODE ON! You now test bonus: Double|';

    if bNewConscription then
      Result := 'DEBUG MODE ON! You now test bonus: New Conscription|';

    if bReinforce then
      Result := 'DEBUG MODE ON! You now test bonus: Reinforcement|';

    if bReborn then
      Result := 'DEBUG MODE ON! You now test bonus: Reborn|';

    if bNewborn then
      Result := 'DEBUG MODE ON! You now test bonus: Newborn Ally|';

  end;
end;


procedure GetInitialAttack;
var
  AIGroup: Integer;
begin

  AIGroup := States.GroupAt(41, 21);
  Actions.GroupOrderWalk(AIGroup, 58, 54, 4);

  AIGroup := States.GroupAt(112, 22);
  Actions.GroupOrderWalk(AIGroup, 93, 54, 4);

  AIGroup := States.GroupAt(135, 38);
  Actions.GroupOrderWalk(AIGroup, 97, 58, 6);

  AIGroup := States.GroupAt(132, 112);
  Actions.GroupOrderWalk(AIGroup, 98, 94, 6);

  AIGroup := States.GroupAt(113, 127);
  Actions.GroupOrderWalk(AIGroup, 94, 97, 0);

  AIGroup := States.GroupAt(37, 126);
  Actions.GroupOrderWalk(AIGroup, 58, 97, 0);

  AIGroup := States.GroupAt(16, 112);
  Actions.GroupOrderWalk(AIGroup, 52, 93, 2);

  AIGroup := States.GroupAt(13, 39);
  Actions.GroupOrderWalk(AIGroup, 53, 57, 2);

end;


procedure OnMissionStart;
var
  Houses: array of Integer;
begin
  AutoFeed;

  GetInitialAttack;

  if DEBUG_MODE then
    for I := 0 to 3 do
      if States.PlayerEnabled(I) then
        Actions.FogRevealAll(I);

  Wave := 1;
  WaveTime := 1200;
  General := States.UnitAt(75, 77);
  AIBarracks := States.HouseAt(75, 76);

  Barracks[0] := States.HouseAt(63, 71);
  Barracks[1] := States.HouseAt(63, 80);
  Barracks[2] := States.HouseAt(88, 80);
  Barracks[3] := States.HouseAt(88, 71);

  SpawnX[0] := 46;
  SpawnX[1] := 46;
  SpawnX[2] := 105;
  SpawnX[3] := 105;
  SpawnY[0] := 46;
  SpawnY[1] := 105;
  SpawnY[2] := 105;
  SpawnY[3] := 46;

  RescueTileX[0] := 46;
  RescueTileX[1] := 46;
  RescueTileX[2] := 105;
  RescueTileX[3] := 105;
  RescueTileY[0] := 46;
  RescueTileY[1] := 105;
  RescueTileY[2] := 105;
  RescueTileY[3] := 46;

  Direction[0] := 4;
  Direction[1] := 0;
  Direction[2] := 0;
  Direction[3] := 4;

  RescueSquadPositionX[0][0] := 44;
  RescueSquadPositionX[0][1] := 44;
  RescueSquadPositionX[0][2] := 48;
  RescueSquadPositionX[0][3] := 52;
  RescueSquadPositionX[0][4] := 49;

  RescueSquadPositionX[1][0] := 44;
  RescueSquadPositionX[1][1] := 44;
  RescueSquadPositionX[1][2] := 49;
  RescueSquadPositionX[1][3] := 49;
  RescueSquadPositionX[1][4] := 52;

  RescueSquadPositionX[2][0] := 107;
  RescueSquadPositionX[2][1] := 107;
  RescueSquadPositionX[2][2] := 103;
  RescueSquadPositionX[2][3] := 102;
  RescueSquadPositionX[2][4] := 99;

  RescueSquadPositionX[3][0] := 107;
  RescueSquadPositionX[3][1] := 107;
  RescueSquadPositionX[3][2] := 102;
  RescueSquadPositionX[3][3] := 99;
  RescueSquadPositionX[3][4] := 102;

  RescueSquadPositionY[0][0] := 45;
  RescueSquadPositionY[0][1] := 50;
  RescueSquadPositionY[0][2] := 46;
  RescueSquadPositionY[0][3] := 50;
  RescueSquadPositionY[0][4] := 54;

  RescueSquadPositionY[1][0] := 101;
  RescueSquadPositionY[1][1] := 106;
  RescueSquadPositionY[1][2] := 105;
  RescueSquadPositionY[1][3] := 97;
  RescueSquadPositionY[1][4] := 101;

  RescueSquadPositionY[2][0] := 101;
  RescueSquadPositionY[2][1] := 106;
  RescueSquadPositionY[2][2] := 105;
  RescueSquadPositionY[2][3] := 97;
  RescueSquadPositionY[2][4] := 101;

  RescueSquadPositionY[3][0] := 45;
  RescueSquadPositionY[3][1] := 50;
  RescueSquadPositionY[3][2] := 46;
  RescueSquadPositionY[3][3] := 50;
  RescueSquadPositionY[3][4] := 54;

  RescueSquadFormation[0][0] := 5;
  RescueSquadFormation[0][1] := 5;
  RescueSquadFormation[0][2] := 4;
  RescueSquadFormation[0][3] := 5;
  RescueSquadFormation[0][4] := 5;

  RescueSquadFormation[1][0] := 5;
  RescueSquadFormation[1][1] := 5;
  RescueSquadFormation[1][2] := 4;
  RescueSquadFormation[1][3] := 5;
  RescueSquadFormation[1][4] := 5;
 
  RescueSquadFormation[2][0] := 5;
  RescueSquadFormation[2][1] := 5;
  RescueSquadFormation[2][2] := 4;
  RescueSquadFormation[2][3] := 5;
  RescueSquadFormation[2][4] := 5;

  RescueSquadFormation[3][0] := 5;
  RescueSquadFormation[3][1] := 5;
  RescueSquadFormation[3][2] := 4;
  RescueSquadFormation[3][3] := 5;
  RescueSquadFormation[3][4] := 5;

  RallyPointX[4] := 75;
  RallyPointX[5] := 130;
  RallyPointX[6] := 75;
  RallyPointX[7] := 20;
  RallyPointY[4] := 20;
  RallyPointY[5] := 75;
  RallyPointY[6] := 130;
  RallyPointY[7] := 75;

  AttackPointX[4] := 75;
  AttackPointX[5] := 95;
  AttackPointX[6] := 75;
  AttackPointX[7] := 55;
  AttackPointY[4] := 55;
  AttackPointY[5] := 75;
  AttackPointY[6] := 95;
  AttackPointY[7] := 75;

  AISpawnX[0][4] := 65;
  AISpawnX[1][4] := 75;
  AISpawnX[2][4] := 85;

  AISpawnY[0][4] := 10;
  AISpawnY[1][4] := 10;
  AISpawnY[2][4] := 10;

  AISpawnX[0][5] := 140;
  AISpawnX[1][5] := 140;
  AISpawnX[2][5] := 140;

  AISpawnY[0][5] := 65;
  AISpawnY[1][5] := 75;
  AISpawnY[2][5] := 85;

  AISpawnX[0][6] := 65;
  AISpawnX[1][6] := 75;
  AISpawnX[2][6] := 85;

  AISpawnY[0][6] := 140;
  AISpawnY[1][6] := 140;
  AISpawnY[2][6] := 140;

  AISpawnX[0][7] := 10;
  AISpawnX[1][7] := 10;
  AISpawnX[2][7] := 10;

  AISpawnY[0][7] := 65;
  AISpawnY[1][7] := 75;
  AISpawnY[2][7] := 85;

  bImmediateKill := False;
  bDouble := False;
  bNewConscription := False; 
  bReinforce := False;
  bReborn := False;
  bNewborn := False;
  Check := False;
  bMsg := False;
  bRescueMsg := False;
  bRanged := False;

  for I := 0 to 3 do
  for K := 0 to 3 do
    if (States.PlayerEnabled(I))
    and (States.PlayerEnabled(K))
    and (I <> K) then 
    begin
      Actions.PlayerAllianceChange(I, K, True, True);
      Actions.PlayerAllianceChange(K, I, True, True);
    end;

  for I := 0 to 3 do
    if States.PlayerEnabled(I) then 
    begin
      RescuesCount[I] := RESCUES_PER_PLAYER;
      RescuesDelay[I] := 0;
      RescueArmy[I] := RESCUE_ARMY_COUNT;
      RescueRecruits[I] := RESCUE_RECRUITS_COUNT;
      Scores[I] := 0;
      Houses := States.PlayerGetAllHouses(I);
      for K := 0 to Length(Houses) - 1 do
        if States.HouseType(Houses[K]) = 13 then
          Actions.HouseSchoolQueueAdd(Houses[K], 13, 1);
    end;

    for I := 0 to 3 do
    for K := 15 to 23 do    
      if States.PlayerEnabled(I) then
      begin
        Actions.UnitBlock(I, K, True);
        Unlocked[I][K] := False;
    end;
end;


procedure CheckBonus;
begin
  case States.KaMRandomI(140) of

    0..19: begin
             bImmediateKill := True;
             if not bMsg then
             begin
               Actions.ShowMsg(-1, '<$6> ' + '<$7>: ' + '<$13>');
               bMsg := True;
             end;
           end;

    20..39: begin
              bDouble := True;
              if not bMsg then
              begin
                Actions.ShowMsg(-1, '<$6> ' + '<$8>: ' + '<$14>');
                bMsg := True;
              end;
            end;

    40..59: begin
              bNewConscription := True;
              if not bMsg then
              begin
                Actions.ShowMsg(-1, '<$6> ' + '<$9>: ' + '<$15>');
                bMsg := True;
              end;
            end;

    60..79: begin
              bReinforce := True;
              if not bMsg then
              begin
                Actions.ShowMsg(-1, '<$6> ' + '<$10>: ' + '<$16>');
                bMsg := True;
              end;
            end;

    80..99: begin
              bReborn := True;
              if not bMsg then
              begin
                Actions.ShowMsg(-1, '<$6> ' + '<$11>: ' + '<$17>');
                bMsg := True;
              end;
            end;

    100..119: begin
                bNewborn := True;
                if not bMsg then
                begin
                  Actions.ShowMsg(-1, '<$6> ' + '<$12>: ' + '<$18>');
                  bMsg := True;
                end;
              end;

    120..139: begin
                bRanged := True;
                if not bMsg then
              begin
                Actions.ShowMsg(-1, '<$6> ' + '<$52>: ' + '<$53>');
                bMsg := True;
              end;
            end;

  end;
end;


procedure AddRecruits;
begin
  for I := 0 to 3 do
    if (States.PlayerEnabled(I))
    and ((not States.HouseDestroyed(Barracks[I]))
    or (Barracks[I] <> -1)) then
    begin
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      if States.KaMRandom < BONUS_CHANCE then
      begin
        Actions.HouseBarracksGiveRecruit(Barracks[I]);
        Actions.HouseBarracksGiveRecruit(Barracks[I]);
        Actions.HouseBarracksGiveRecruit(Barracks[I]);
        Actions.HouseBarracksGiveRecruit(Barracks[I]);
      end;
    end;
end;


procedure AddRecruits10;
begin
  for I := 0 to 3 do
    if (States.PlayerEnabled(I))
    and ((not States.HouseDestroyed(Barracks[I]))
    or (Barracks[I] <> -1)) then
    begin
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
      Actions.HouseBarracksGiveRecruit(Barracks[I]);
    end;
end;


function Delay: Integer;
begin
  if States.GameTime < 25200 then
    Result := 1200
  else
    if Wave < 30 then
      Result := 1800;
    if Wave = 30 then
      Result := 0;
end;


function WaveName: AnsiString;
begin
  case Wave of
    1:   Result := '<$19>';
    2:   Result := '<$20>';
    3:   Result := '<$21>';
    4:   Result := '<$22>';
    5:   Result := '<$23>';
    6:   Result := '<$24>';
    7:   Result := '<$25>';
    8:   Result := '<$26>';
    9:   Result := '<$27>';
    10:  Result := '<$28>';
    11:  Result := '<$29>';
    12:  Result := '<$30>';
    13:  Result := '<$31>';
    14:  Result := '<$32>';
    15:  Result := '<$33>';
    16:  Result := '<$34>';
    17:  Result := '<$35>';
    18:  Result := '<$36>';
    19:  Result := '<$37>';
    20:  Result := '<$38>';
    21:  Result := '<$39>';
    22:  Result := '<$40>';
    23:  Result := '<$41>';
    24:  Result := '<$42>';
    25:  Result := '<$43>';
    26:  Result := '<$44>';
    27:  Result := '<$45>';
    28:  Result := '<$46>';
    29:  Result := '<$47>';
    30:  Result := '<$48>'
    else Result := '';
  end;
end;


function HasHouses(aPlayer: Integer): Boolean;
begin
  if States.PlayerEnabled(aPlayer) then
    Result := Length(States.PlayerGetAllHouses(aPlayer)) > 0
  else
    Result := False;
end;


function HasUnits(aPlayer: Integer): Boolean;
begin
  if States.PlayerEnabled(aPlayer) then
    Result := Length(States.PlayerGetAllUnits(aPlayer)) > 0
  else
    Result := False;
end;


function TotalArmyCount: Integer;
begin
  Result := 0;
  for I := 0 to 3 do
    if States.PlayerEnabled(I) then
      Result := Result + States.StatArmyCount(I);
end;


procedure GetTimer;
begin
  if WaveTime > 0 then
    WaveTime := WaveTime - 1
  else
    WaveTime := Delay;
end;


procedure OnUnitTrained(aUnitID: Integer);
var
  {Rebel, Vaga,} SchoolHouse: Integer;
  //Groups: array of Integer;
begin
  Actions.UnitHungerSet(aUnitID, States.UnitMaxHunger);
  SchoolHouse := States.HouseAt(States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) - 1);
  if SchoolHouse <> - 1 then
    if States.HouseSchoolQueue(SchoolHouse, 5) = - 1 then
      Actions.HouseSchoolQueueAdd(SchoolHouse, 13, 1);

  if (States.UnitType(aUnitID) = 13) then
    if States.KaMRandom < (0.1 + 0.1 * Byte(bNewConscription)) then
      Actions.GiveUnit(States.UnitOwner(aUnitID), 13, States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) + 1, 5);
  
  {if (States.UnitType(aUnitID) = 13)
  and (Wave <= 14) then
    if States.KaMRandom < 0.300 then
    begin
      Rebel := Actions.GiveGroup(States.UnitOwner(aUnitID), 24, States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) + 1, 4, 1, 1);
      Actions.GroupHungerSet(Rebel, States.UnitMaxHunger);
      Groups := States.PlayerGetAllGroups(States.UnitOwner(aUnitID));
      for I := 0 to Length(Groups) - 1 do
        if States.GroupType(Groups[I]) = 1 then
        begin
          Actions.GroupOrderLink(Rebel, Groups[I]);
          Actions.GroupSetFormation(Groups[I], 1 + Round(sqrt(States.GroupMemberCount(Groups[I]))));
        end;
    end;

  if (States.UnitType(aUnitID) = 13)
  and (Wave > 14) then
    if States.KaMRandom < 0.300 then
    begin
      Vaga := Actions.GiveGroup(States.UnitOwner(aUnitID), 27, States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) + 1, 4, 1, 1);
      Actions.GroupHungerSet(Vaga, States.UnitMaxHunger);
      Groups := States.PlayerGetAllGroups(States.UnitOwner(aUnitID));
      for I := 0 to Length(Groups) - 1 do
        if States.GroupType(Groups[I]) = 3 then
        begin
          Actions.GroupOrderLink(Vaga, Groups[I]);
          Actions.GroupSetFormation(Groups[I], 1 + Round(sqrt(States.GroupMemberCount(Groups[I]))));
        end;
    end;}
end;


function InRange(Number, Min, Max: Integer): Boolean;
begin
  Result := ((Number >= Min) and (Number <= Max));
end;


procedure ContinueAttack;
var
  Groups: array of Integer;
  X, Y, Player: Integer;
begin
  for I := 4 to 7 do
  begin
    Groups := States.PlayerGetAllGroups(I);

    for K := 0 to Length(Groups) - 1 do
      if (Groups[K] <> -1)
      and (States.GroupMember(Groups[K], 0) <> -1) then
        if (InRange(States.UnitPositionX(States.GroupMember(Groups[K], 0)), 52, 99))
        and (InRange(States.UnitPositionY(States.GroupMember(Groups[K], 0)), 52, 99)) then
        begin
          X := States.UnitPositionX(States.GroupMember(Groups[K], 0));
          Y := States.UnitPositionY(States.GroupMember(Groups[K], 0));
          Player := States.KaMRandomI(4);
          if HasHouses(Player) then
            Actions.GroupOrderAttackHouse(Groups[K], States.ClosestHouseMultipleTypes(Player, X, Y, [11, 13, 17, 21, 27]));
          if States.KaMRandom > 0.9 then
            if ((not States.UnitDead(General)) or (General <> -1)) then
              Actions.GroupOrderAttackUnit(Groups[K], General);
          if States.KaMRandom < 0.1 then
            if HasUnits(Player) then
              Actions.GroupOrderAttackUnit(Groups[K], States.ClosestUnitMultipleTypes(Player, X, Y, [0, 9, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]));
          if States.KaMRandomI(10) = 5 then
            if ((not States.HouseDestroyed(AIBarracks)) or (AIBarracks <> -1)) then
              Actions.GroupOrderAttackHouse(Groups[K], AIBarracks);
        end;
  end;
end;


procedure AttackCenter;
var
  Groups: array of Integer;
  K: Integer;
begin
  Groups := States.PlayerGetAllGroups(4);
  for K := 0 to length(Groups) - 1 do
    if (Groups[K] <> -1)
    and (States.GroupMember(Groups[K], 0) <> -1) then
      if (InRange(States.UnitPositionX(States.GroupMember(Groups[K], 0)), RallyPointX[4] - 1, RallyPointX[4] + 1))
      and (InRange(States.UnitPositionY(States.GroupMember(Groups[K], 0)), RallyPointY[4] - 1, RallyPointY[4] + 1)) then
        Actions.GroupOrderWalk(Groups[K], AttackPointX[4], AttackPointY[4], 4);

  Groups := States.PlayerGetAllGroups(5);
  for K := 0 to length(Groups) - 1 do
    if (Groups[K] <> -1)
    and (States.GroupMember(Groups[K], 0) <> -1) then
      if (InRange(States.UnitPositionX(States.GroupMember(Groups[K], 0)), RallyPointX[5] - 1, RallyPointX[5] + 1))
      and (InRange(States.UnitPositionY(States.GroupMember(Groups[K], 0)), RallyPointY[5] - 1, RallyPointY[5] + 1)) then
        Actions.GroupOrderWalk(Groups[K], AttackPointX[5], AttackPointY[5], 6);

  Groups := States.PlayerGetAllGroups(6);
  for K := 0 to length(Groups) - 1 do
    if (Groups[K] <> -1)
    and (States.GroupMember(Groups[K], 0) <> -1) then
      if (InRange(States.UnitPositionX(States.GroupMember(Groups[K], 0)), RallyPointX[6] - 1, RallyPointX[6] + 1))
      and (InRange(States.UnitPositionY(States.GroupMember(Groups[K], 0)), RallyPointY[6] - 1, RallyPointY[6] + 1)) then
        Actions.GroupOrderWalk(Groups[K], AttackPointX[6], AttackPointY[6], 0);

  Groups := States.PlayerGetAllGroups(7);
  for K := 0 to length(Groups) - 1 do
    if (Groups[K] <> -1)
    and (States.GroupMember(Groups[K], 0) <> -1) then
      if (InRange(States.UnitPositionX(States.GroupMember(Groups[K], 0)), RallyPointX[7] - 1, RallyPointX[7] + 1))
      and (InRange(States.UnitPositionY(States.GroupMember(Groups[K], 0)), RallyPointY[7] - 1, RallyPointY[7] + 1)) then
        Actions.GroupOrderWalk(Groups[K], AttackPointX[7], AttackPointY[7], 2);
end;


procedure UnlockWarriors;
begin
  for I := 0 to 3 do
  begin
    if Scores[I] >= 50 then
      if not Unlocked[I][19] then
      begin
        Actions.UnitBlock(I, 19, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(19)]);
        Unlocked[I][19] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 100 then
      if not Unlocked[I][15] then
      begin
        Actions.UnitBlock(I, 15, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(15)]);
        Unlocked[I][15] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 160 then
      if not Unlocked[I][17] then
      begin
        Actions.UnitBlock(I, 17, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(17)]);
        Unlocked[I][17] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 250 then
      if not Unlocked[I][18] then
      begin
        Actions.UnitBlock(I, 18, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(18)]);
        Unlocked[I][18] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 400 then
      if not Unlocked[I][20] then
      begin
        Actions.UnitBlock(I, 20, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(20)]);
        Unlocked[I][20] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 550 then
      if not Unlocked[I][21] then
      begin
        Actions.UnitBlock(I, 21, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(21)]);
        Unlocked[I][21] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 700 then
      if not Unlocked[I][16] then
      begin
        Actions.UnitBlock(I, 16, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(16)]);
        Unlocked[I][16] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 1000 then
      if not Unlocked[I][23] then
      begin
        Actions.UnitBlock(I, 23, False);
        Actions.ShowMsgFormatted(I, '<$3>' + ' <$4>', [States.UnitTypeName(23) + ', ' + States.UnitTypeName(26)]);
        Unlocked[I][23] := True;
      end;
  end;

  for I := 0 to 3 do
  begin
    if Scores[I] >= 1250 then
      if not Unlocked[I][22] then
      begin
        Actions.UnitBlock(I, 22, False);
        Actions.ShowMsgFormatted(I, '<$3>', [States.UnitTypeName(22)]);
        Unlocked[I][22] := True;
      end;
  end;
end;


function FindClosestGroup(aPlayer, aX, aY, aType, aRadius: Integer): Integer; 
var 
  Groups: array of Integer;
  G, BestDistanceSqr, ThisDistanceSqr, DX, DY: Integer;
begin
  Result := -1;
  Groups := States.PlayerGetAllGroups(aPlayer);
  for I := 0 to Length(Groups) - 1 do
  begin
    G := Groups[I];
    DX := aX - States.UnitPositionX(States.GroupMember(G, 0));
    DY := aY - States.UnitPositionY(States.GroupMember(G, 0));
    ThisDistanceSqr := (DX * DX) + (DY * DY);
    if ((Abs(DX) < aRadius)
    and (Abs(DY) < aRadius))
    and ((Result = -1)
    or (ThisDistanceSqr< BestDistanceSqr))
    and (States.GroupType(G) = aType) then
    begin
      BestDistanceSqr := ThisDistanceSqr;
      Result := Groups[I];
    end;
  end;
end;


procedure OnUnitDied(aUnitID, aKillerIndex: Integer);
var
  Addition, GroupToLink, I, Owner, Owner1, GT, UT: Integer;
  Groups: array of Integer;
begin
  if (aKillerIndex = -1)
  and (States.UnitHunger(aUnitID) > 0) then
    Exit;

  if (InRange(States.UnitOwner(aUnitID), 4, 7))
  and (InRange(aKillerIndex, 0, 3)) then
    Scores[aKillerIndex] := Scores[aKillerIndex] + 1;

  UnlockWarriors;

  if InRange(States.UnitOwner(aUnitID), 0, 3) then
    Owner := States.UnitOwner(aUnitID);

  if InRange(States.UnitOwner(aUnitID), 4, 7) then
    Owner1 := aKillerIndex;

  if InRange(States.UnitType(aUnitID), 14, 27) then
  begin
    UT := States.UnitType(aUnitID);

    if bReborn then
    begin
      if States.KaMRandom < REBORN_CHANCE then
      begin
        if (InRange(States.UnitOwner(aUnitID), 0, 3)) then
        begin
          Addition := Actions.GiveGroup(Owner, UT, SpawnX[Owner], SpawnY[Owner], 4, 1, 1);
          GT := States.GroupType(Addition);
          Actions.GroupHungerSet(Addition, States.UnitMaxHunger);
          Groups := States.PlayerGetAllGroups(Owner);
          for I := Length(Groups) - 1 downto 0 do            
            if (Addition > 0)
            and (States.GroupType(Groups[I]) = GT)
            //and (Groups[I] = FindClosestGroup(Owner, SpawnX[Owner], SpawnY[Owner], GT, 5))
            and (Abs(States.UnitPositionY(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionY(States.GroupMember(Addition, 0))) <= 6)
            and (Abs(States.UnitPositionX(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionX(States.GroupMember(Addition, 0))) <= 6) then
            begin
              GroupToLink := Groups[I];
              if GroupToLink > 0 then
                begin
                  Actions.GroupOrderLink(Addition, GroupToLink);
                  Actions.GroupSetFormation(GroupToLink, 1 + Round(sqrt(States.GroupMemberCount(GroupToLink))));
                end;
            end;
        end;
      end;
    end;

    if bNewborn then
    begin
      if States.KaMRandom < NEWBORN_CHANCE then
      begin
        if (InRange(aKillerIndex, 0, 3))
        and (InRange(States.UnitOwner(aUnitID), 4, 7)) then
        begin
          Addition := Actions.GiveGroup(Owner1, UT, SpawnX[Owner1], SpawnY[Owner1], 4, 1, 1);
          GT := States.GroupType(Addition);
          Actions.GroupHungerSet(Addition, States.UnitMaxHunger);
          Groups := States.PlayerGetAllGroups(Owner1);
          for I := Length(Groups) - 1 downto 0 do
            if (Addition > 0)
            and (States.GroupType(Groups[I]) = GT)
            //and (Groups[I] = FindClosestGroup(Owner1, SpawnX[Owner1], SpawnY[Owner1], GT, 5))
            and (Abs(States.UnitPositionY(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionY(States.GroupMember(Addition, 0))) <= 6)
            and (Abs(States.UnitPositionX(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionX(States.GroupMember(Addition, 0))) <= 6) then
            begin
              GroupToLink := Groups[I];
              if GroupToLink > 0 then
                begin
                  Actions.GroupOrderLink(Addition, GroupToLink);
                  Actions.GroupSetFormation(GroupToLink, 1 + Round(sqrt(States.GroupMemberCount(GroupToLink))));
                end;
            end;
        end;
      end;
    end;
  end;
end;


procedure OnUnitWounded(aUnitID, aAttacker: Integer);
begin
  if bImmediateKill then
  begin
    if States.KaMRandom < KILL_CHANCE then
    begin
      if InRange(States.UnitOwner(aAttacker), 0, 3) then
        inc(Scores[States.UnitOwner(aAttacker)]);
      if InRange(States.UnitOwner(aUnitID), 4, 7) then
        Actions.UnitKill(aUnitID, False);
    end;
  end;
end;


function BarbDouble: Integer;
begin
  if States.KaMRandom < DOUBLE_CHANCE then
    Result := 1 + Byte(bDouble)
  else
    Result := 1;
end;


procedure OnWarriorEquipped(aUnitID, aGroupID: Integer);
var
  Rogue, Barb, Owner, Addition, GroupToLink: Integer;
  Groups, Groups1: array of Integer;
begin
  Owner := States.UnitOwner(aUnitID);

  if bDouble then
  begin
    if States.KaMRandom < DOUBLE_CHANCE then
    begin
      if (States.UnitType(aUnitID) >= 14)
      and not (InRange(States.UnitType(aUnitID), 17, 18)) then
      begin 
        Addition := Actions.GiveGroup(Owner, States.UnitType(aUnitID), States.HousePositionX(Barracks[States.UnitOwner(aUnitID)]), States.HousePositionY(Barracks[States.UnitOwner(aUnitID)]) + 1, 4, 1, 1);
        GroupToLink := aGroupID;
        if GroupToLink > 0 then
        begin
          Actions.GroupHungerSet(Addition, States.UnitMaxHunger);
          Actions.GroupOrderLink(Addition, GroupToLink);
          Actions.GroupSetFormation(GroupToLink, 1 + Round(sqrt(States.GroupMemberCount(GroupToLink))));
        end;
      end
      else
      if InRange(States.UnitType(aUnitID), 17, 18)
      and (States.StatUnitMultipleTypesCount(Owner, [17, 18]) <= MAX_RANGED) then
      begin 
        Addition := Actions.GiveGroup(Owner, States.UnitType(aUnitID), States.HousePositionX(Barracks[States.UnitOwner(aUnitID)]), States.HousePositionY(Barracks[States.UnitOwner(aUnitID)]) + 1, 4, 1, 1);
        GroupToLink := aGroupID;
        if GroupToLink > 0 then
        begin
          Actions.GroupHungerSet(Addition, States.UnitMaxHunger);
          Actions.GroupOrderLink(Addition, GroupToLink);
          Actions.GroupSetFormation(GroupToLink, 1 + Round(sqrt(States.GroupMemberCount(GroupToLink))));
        end;
      end;
    end;
  end;

  if bRanged then
  begin
    if States.KaMRandom < RANGED_CHANCE then
    begin
      if InRange(States.UnitType(aUnitID), 14, 16)
      and (States.StatUnitMultipleTypesCount(Owner, [17, 18]) <= MAX_RANGED) then
      begin 
        Addition := Actions.GiveGroup(Owner, States.KaMRandomI(2) + 17, States.HousePositionX(Barracks[States.UnitOwner(aUnitID)]), States.HousePositionY(Barracks[States.UnitOwner(aUnitID)]) + 1, 4, 1, 1);
        Actions.GroupHungerSet(Addition, States.UnitMaxHunger);
        Groups := States.PlayerGetAllGroups(Owner);
        for I := Length(Groups) - 1 downto 0 do
          if (States.GroupType(Groups[I]) = 2)
          and (Abs(States.UnitPositionY(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionY(States.GroupMember(Addition, 0))) <= 6)
          and (Abs(States.UnitPositionX(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionX(States.GroupMember(Addition, 0))) <= 6) then
          begin
            Actions.GroupOrderLink(Addition, Groups[I]);
            Actions.GroupSetFormation(Groups[I], 1 + Round(sqrt(States.GroupMemberCount(Groups[I]))));
          end;
      end;
    end;
  end;

  if (Unlocked[Owner][23])
  and (States.HouseRepair(Barracks[Owner]))
  and (States.HouseResourceAmount(Barracks[Owner], 20) > 3)
  and (States.UnitType(aUnitID) = 14) then
  begin
    if States.KaMRandom < 0.5 then
      Barb := Actions.GiveGroup(States.UnitOwner(aUnitID), 23, States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) + 1, 4, BarbDouble, 1)
    else
      Barb := Actions.GiveGroup(States.UnitOwner(aUnitID), 26, States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) + 1, 4, BarbDouble, 1);
    Actions.UnitKill(aUnitID, True);
    Actions.HouseTakeWaresFrom(Barracks[Owner], 20, 3);
    Actions.GroupHungerSet(Barb, States.UnitMaxHunger);
    Groups := States.PlayerGetAllGroups(Owner);
    for I := Length(Groups) - 1 downto 0 do
      if (States.GroupType(Groups[I]) = 0)
      and (Abs(States.UnitPositionY(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionY(States.GroupMember(Barb, 0))) <= 6)
      and (Abs(States.UnitPositionX(States.GroupMember(Groups[I], States.KaMRandomI(States.GroupMemberCount(Groups[I])))) - States.UnitPositionX(States.GroupMember(Barb, 0))) <= 6) then
      begin
        Actions.GroupOrderLink(Barb, Groups[I]);
        Actions.GroupSetFormation(Groups[I], 1 + Round(sqrt(States.GroupMemberCount(Groups[I]))));
      end;
  end;

  Actions.UnitHungerSet(aUnitID, States.UnitMaxHunger);
  if States.UnitType(aUnitID) = 14 then
    if States.KaMRandom > 0.600 then
    begin
      Rogue := Actions.GiveGroup(States.UnitOwner(aUnitID), 25, States.UnitPositionX(aUnitID), States.UnitPositionY(aUnitID) + 1, 4, 1, 1);
      Actions.GroupHungerSet(Rogue, States.UnitMaxHunger);
      Groups1 := States.PlayerGetAllGroups(States.UnitOwner(aUnitID));
      for I := 0 to Length(Groups1) - 1 do
        if States.GroupType(Groups1[I]) = 2 then
        begin
          Actions.GroupOrderLink(Rogue, Groups1[I]);
          Actions.GroupSetFormation(Groups1[I], 1 + Round(sqrt(States.GroupMemberCount(Groups1[I]))));
        end;
    end;
end;


procedure GetReinforce;
var
  R: array[0..3] of Integer;
begin
  for I := 0 to 3 do
  begin
    if States.PlayerEnabled(I)
    and not (States.PlayerDefeated(I)) then
      begin
        if States.KaMRandom < 0.33 then
          R[I] := Actions.GiveGroup(I, 16, SpawnX[I], SpawnY[I], 4, 12 + States.KaMRandomI(5), 3 + States.KaMRandomI(3))
        else
        if InRange(Round(100 * States.KaMRandom), 33, 66) then 
          R[I] := Actions.GiveGroup(I, 20, SpawnX[I], SpawnY[I], 4, 12 + States.KaMRandomI(5), 3 + States.KaMRandomI(3))
        else
          R[I] := Actions.GiveGroup(I, 22, SpawnX[I], SpawnY[I], 4, 12 + States.KaMRandomI(5), 3 + States.KaMRandomI(3));
        Actions.GroupHungerSet(R[I], States.UnitMaxHunger);
      end;
  end;
end;

    
procedure GetAttacks;
begin
  if Wave < MAX_WAVE then
  begin
    Wave := Wave + 1;
    Actions.PlayWAV(-1, 'NEWWAVE', 1);
  end;

  case Wave of
    2: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 12);

         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[0][4], AISpawnY[0][4], 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[1][4], AISpawnY[1][4], 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[2][4], AISpawnY[2][4], 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[0][5], AISpawnY[0][5], 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[1][5], AISpawnY[1][5], 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[2][5], AISpawnY[2][5], 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[0][6], AISpawnY[0][6], 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[1][6], AISpawnY[1][6], 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[2][6], AISpawnY[2][6], 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[0][7], AISpawnY[0][7], 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[1][7], AISpawnY[1][7], 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[2][7], AISpawnY[2][7], 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    3: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 12);

         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[0][4], AISpawnY[0][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[1][4], AISpawnY[1][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[2][4], AISpawnY[2][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[0][5], AISpawnY[0][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[1][5], AISpawnY[1][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 14, 140, 95, 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[0][6], AISpawnY[0][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[1][6], AISpawnY[1][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[2][6], AISpawnY[2][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[0][7], AISpawnY[0][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[1][7], AISpawnY[1][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[2][7], AISpawnY[2][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    4: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 12);

         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[0][4], AISpawnY[0][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 19, AISpawnX[1][4], AISpawnY[1][4], 4, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[2][4], AISpawnY[2][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[0][5], AISpawnY[0][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 19, AISpawnX[1][5], AISpawnY[1][5], 6, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[2][5], AISpawnY[2][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[0][6], AISpawnY[0][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 19, AISpawnX[1][6], AISpawnY[1][6], 0, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[2][6], AISpawnY[2][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[0][7], AISpawnY[0][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 19, AISpawnX[1][7], AISpawnY[1][7], 2, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[2][7], AISpawnY[2][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    5: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 12);

         AIGroup := Actions.GiveGroup(4, 19, AISpawnX[0][4], AISpawnY[0][4], 4, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 14, AISpawnX[1][4], AISpawnY[1][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 19, AISpawnX[2][4], AISpawnY[2][4], 4, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 19, AISpawnX[0][5], AISpawnY[0][5], 6, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 14, AISpawnX[1][5], AISpawnY[1][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 19, AISpawnX[2][5], AISpawnY[2][5], 6, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 19, AISpawnX[0][6], AISpawnY[0][6], 0, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 14, AISpawnX[1][6], AISpawnY[1][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 19, AISpawnX[2][6], AISpawnY[2][6], 0, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 19, AISpawnX[0][7], AISpawnY[0][7], 2, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 14, AISpawnX[1][7], AISpawnY[1][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 19, AISpawnX[2][7], AISpawnY[2][7], 2, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    6: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 12);

         AIGroup := Actions.GiveGroup(4, 19, AISpawnX[0][4], AISpawnY[0][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[1][4], AISpawnY[1][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 19, AISpawnX[2][4], AISpawnY[2][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 19, AISpawnX[0][5], AISpawnY[0][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[1][5], AISpawnY[1][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 19, AISpawnX[2][5], AISpawnY[2][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 19, AISpawnX[0][6], AISpawnY[0][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[1][6], AISpawnY[1][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 19, AISpawnX[2][6], AISpawnY[2][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 19, AISpawnX[0][7], AISpawnY[0][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[1][7], AISpawnY[1][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 19, AISpawnX[2][7], AISpawnY[2][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    7: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 12);

         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[0][4], AISpawnY[0][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 19, AISpawnX[1][4], AISpawnY[1][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[2][4], AISpawnY[2][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[0][5], AISpawnY[0][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 19, AISpawnX[1][5], AISpawnY[1][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[2][5], AISpawnY[2][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[0][6], AISpawnY[0][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 19, AISpawnX[1][6], AISpawnY[1][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[2][6], AISpawnY[2][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[0][7], AISpawnY[0][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 19, AISpawnX[1][7], AISpawnY[1][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[2][7], AISpawnY[2][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    8: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 15);

         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[0][4], AISpawnY[0][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[1][4], AISpawnY[1][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[2][4], AISpawnY[2][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[0][5], AISpawnY[0][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[1][5], AISpawnY[1][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[2][5], AISpawnY[2][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[0][6], AISpawnY[0][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[1][6], AISpawnY[1][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[2][6], AISpawnY[2][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[0][7], AISpawnY[0][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[1][7], AISpawnY[1][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[2][7], AISpawnY[2][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    9: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 15);

         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[0][4], AISpawnY[0][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 17, AISpawnX[1][4], AISpawnY[1][4], 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[2][4], AISpawnY[2][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[0][5], AISpawnY[0][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 17, AISpawnX[1][5], AISpawnY[1][5], 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[2][5], AISpawnY[2][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[0][6], AISpawnY[0][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 17, AISpawnX[1][6], AISpawnY[1][6], 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[2][6], AISpawnY[2][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[0][7], AISpawnY[0][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 17, AISpawnX[1][7], AISpawnY[1][7], 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[2][7], AISpawnY[2][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    10: begin

          for I := 0 to 3 do
            if States.PlayerEnabled(I) then
              Actions.GiveWares(I, 7, 15);

         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[0][4], AISpawnY[0][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[1][4], AISpawnY[1][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[2][4], AISpawnY[2][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[0][5], AISpawnY[0][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[1][5], AISpawnY[1][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[2][5], AISpawnY[2][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[0][6], AISpawnY[0][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[1][6], AISpawnY[1][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[2][6], AISpawnY[2][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[0][7], AISpawnY[0][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[1][7], AISpawnY[1][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[2][7], AISpawnY[2][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    11: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 15);

         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[0][4], AISpawnY[0][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[1][4], AISpawnY[1][4], 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 21, AISpawnX[2][4], AISpawnY[2][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[0][5], AISpawnY[0][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[1][5], AISpawnY[1][5], 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 21, AISpawnX[2][5], AISpawnY[2][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[0][6], AISpawnY[0][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[1][6], AISpawnY[1][6], 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 21, AISpawnX[2][6], AISpawnY[2][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[0][7], AISpawnY[0][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[1][7], AISpawnY[1][7], 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 21, AISpawnX[2][7], AISpawnY[2][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    12: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 15);

         AIGroup := Actions.GiveGroup(4, 20, AISpawnX[0][4], AISpawnY[0][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 18, AISpawnX[1][4], AISpawnY[1][4], 4, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);
         AIGroup := Actions.GiveGroup(4, 15, AISpawnX[2][4], AISpawnY[2][4], 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[4], RallyPointY[4], 4);

         AIGroup := Actions.GiveGroup(5, 20, AISpawnX[0][5], AISpawnY[0][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 18, AISpawnX[1][5], AISpawnY[1][5], 6, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);
         AIGroup := Actions.GiveGroup(5, 15, AISpawnX[2][5], AISpawnY[2][5], 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[5], RallyPointY[5], 6);

         AIGroup := Actions.GiveGroup(6, 20, AISpawnX[0][6], AISpawnY[0][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 18, AISpawnX[1][6], AISpawnY[1][6], 0, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);
         AIGroup := Actions.GiveGroup(6, 15, AISpawnX[2][6], AISpawnY[2][6], 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[6], RallyPointY[6], 0);

         AIGroup := Actions.GiveGroup(7, 20, AISpawnX[0][7], AISpawnY[0][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 18, AISpawnX[1][7], AISpawnY[1][7], 2, 6, 3);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
         AIGroup := Actions.GiveGroup(7, 15, AISpawnX[2][7], AISpawnY[2][7], 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, RallyPointX[7], RallyPointY[7], 2);
       end;

    13: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 15);

         AIGroup := Actions.GiveGroup(4, 15, 57, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 15, 93, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 15, 140, 57, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 15, 140, 93, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 15, 57, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 15, 93, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 15, 10, 57, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 15, 10, 93, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 24, 30, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 24, 120, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 24, 140, 30, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 24, 140, 120, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 24, 30, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 24, 120, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 24, 10, 30, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 24, 10, 120, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    14: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 16);

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 21, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 15, 93, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 21, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 15, 140, 93, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 21, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 15, 93, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 21, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 15, 10, 93, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 27, 30, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 27, 120, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 27, 140, 30, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 27, 140, 120, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 27, 30, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 27, 120, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 27, 10, 30, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 27, 10, 120, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    15: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 16);

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 15, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 15, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 15, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 15, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 27, 30, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 27, 120, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 27, 140, 30, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 27, 140, 120, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 27, 30, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 27, 120, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 27, 10, 30, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 27, 10, 120, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    16: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 16);

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 10, 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 140, 75, 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 140, 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 10, 75, 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 15, 30, 10, 4, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 19, 120, 10, 4, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 15, 140, 30, 6, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 19, 140, 120, 6, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 15, 30, 140, 0, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 19, 120, 140, 0, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 15, 10, 30, 2, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 19, 10, 120, 2, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    17: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 16);

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 15, 30, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 15, 120, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 15, 140, 30, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 15, 140, 120, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 15, 30, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 15, 120, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 15, 10, 30, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 15, 10, 120, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    18: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 16);

         if bReinforce then
           GetReinforce;         

         if bNewConscription then
           AddRecruits;         

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 21, 30, 10, 4, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 21, 120, 10, 4, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 21, 140, 30, 6, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 21, 140, 120, 6, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 21, 30, 140, 0, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 21, 120, 140, 0, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 21, 10, 30, 2, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 21, 10, 120, 2, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    19: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 18);

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;         

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 21, 30, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 21, 120, 10, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 21, 140, 30, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 21, 140, 120, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 21, 30, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 21, 120, 140, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 21, 10, 30, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 21, 10, 120, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    20: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
           begin
             Actions.GiveWares(I, 7, 18);
             Actions.GiveWeapons(I, 24, 10);
             Actions.GiveWeapons(I, 25, 10);
             Actions.GiveWeapons(I, 18, 10);
             Actions.GiveWeapons(I, 19, 10);
           end;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 20, 30, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 120, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 30, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 120, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 20, 30, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 120, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 30, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 120, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    21: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 18);

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 16, 30, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 120, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 30, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 120, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 16, 30, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 120, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 30, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 120, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    22: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 20);

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 140, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 10, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    23: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 20);

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 23, 30, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 120, 10, 4, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 23, 140, 30, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 23, 140, 120, 6, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 23, 30, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 120, 140, 0, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 23, 10, 30, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 23, 10, 120, 2, 9, 3);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    24: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 20);

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 20, 57, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 15, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 20, 140, 57, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 135, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 20, 57, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 135, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 20, 10, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 15, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 120, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 120, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 16, 30, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 30, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    25: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
           begin
             Actions.GiveWares(I, 7, 20);
             Actions.GiveWeapons(I, 24, 15);
             Actions.GiveWeapons(I, 25, 15);
             Actions.GiveWeapons(I, 18, 15);
             Actions.GiveWeapons(I, 19, 15);
           end;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 16, 57, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 15, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 57, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 135, 75, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 16, 57, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 135, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 15, 75, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    26: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 20);

         if TotalArmyCount <= MAX_ARMY_COUNT then
           AddRecruits10;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 16, 57, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 57, 15, 4, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 15, 4, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 15, 4, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 135, 57, 6, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 135, 75, 6, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 135, 93, 6, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 16, 57, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 57, 135, 0, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 135, 0, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 135, 0, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 15, 57, 2, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 15, 75, 2, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 15, 93, 2, 10, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 15, 40, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 15, 110, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 15, 15, 4, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 15, 143, 40, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 15, 143, 110, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 23, 135, 15, 6, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 15, 40, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 15, 110, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 135, 135, 0, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 15, 7, 40, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 15, 7, 110, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 23, 15, 135, 2, 8, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    27: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 20);

         if TotalArmyCount <= MAX_ARMY_COUNT then
           AddRecruits10;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 16, 57, 10, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 57, 15, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 15, 4, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 15, 4, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 57, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 135, 57, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 135, 75, 6, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 135, 93, 6, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 16, 57, 140, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 57, 135, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 135, 0, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 135, 0, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 57, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 15, 57, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 15, 75, 2, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 15, 93, 2, 15, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 40, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 110, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 15, 15, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 22, 143, 40, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 143, 110, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 23, 135, 15, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 40, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 110, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 135, 135, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 22, 7, 40, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 7, 110, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 23, 15, 135, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    28: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 24);

         if TotalArmyCount <= MAX_ARMY_COUNT then
           AddRecruits10;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 16, 57, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 57, 15, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 15, 4, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 20, 93, 15, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 135, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 135, 75, 6, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 20, 135, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 16, 57, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 57, 135, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 135, 0, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 20, 93, 135, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 15, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 15, 75, 2, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 20, 15, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 26, 40, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 26, 110, 10, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 15, 15, 4, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 26, 143, 40, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 26, 143, 110, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 23, 135, 15, 6, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 26, 40, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 26, 110, 140, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 135, 135, 0, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 26, 7, 40, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 26, 7, 110, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 23, 15, 135, 2, 12, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    29: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 30);

         if TotalArmyCount <= MAX_ARMY_COUNT then
           AddRecruits10;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 16, 57, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 57, 15, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 18, 75, 15, 4, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 10, 4, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 15, 4, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 135, 57, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 75, 6, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 18, 135, 75, 6, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 135, 93, 6, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 16, 57, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 57, 135, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 140, 0, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 18, 75, 135, 0, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 135, 0, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 15, 57, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 75, 2, 21, 7);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 18, 15, 75, 2, 12, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 15, 93, 2, 20, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 40, 10, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 110, 10, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 26, 15, 15, 4, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 23, 143, 40, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 23, 143, 110, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 26, 135, 15, 6, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 40, 140, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 110, 140, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 26, 135, 135, 0, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 23, 7, 40, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 23, 7, 110, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 26, 15, 135, 2, 16, 4);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;

    30: begin

         for I := 0 to 3 do
           if States.PlayerEnabled(I) then
             Actions.GiveWares(I, 7, 30);

         if TotalArmyCount <= MAX_ARMY_COUNT then
           AddRecruits10;

         if bReinforce then
           GetReinforce;

         if bNewConscription then
           AddRecruits;

         AIGroup := Actions.GiveGroup(4, 16, 57, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 57, 15, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 75, 15, 4, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 23, 75, 10, 4, 40, 10);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 10, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 93, 15, 4, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 55, 4);

         AIGroup := Actions.GiveGroup(5, 16, 140, 59, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 135, 57, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 23, 140, 75, 6, 40, 10);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 22, 135, 75, 6, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 140, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);
         AIGroup := Actions.GiveGroup(5, 16, 135, 93, 6, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 95, 75, 6);

         AIGroup := Actions.GiveGroup(6, 16, 57, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 57, 135, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 23, 75, 140, 0, 40, 10);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 75, 135, 0, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 140, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 93, 135, 0, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 75, 95, 0);

         AIGroup := Actions.GiveGroup(7, 16, 10, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 15, 57, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 23, 10, 75, 2, 40, 10);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 22, 15, 75, 2, 18, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 10, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);
         AIGroup := Actions.GiveGroup(7, 16, 15, 93, 2, 25, 5);
         Actions.GroupOrderWalk(AIGroup, 55, 75, 2);

         AIGroup := Actions.GiveGroup(4, 22, 30, 10, 4, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 22, 120, 10, 4, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 40, 10, 4, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);
         AIGroup := Actions.GiveGroup(4, 16, 110, 10, 4, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 93, 55, 4);
         AIGroup := Actions.GiveGroup(4, 26, 15, 15, 4, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 58, 55, 4);

         AIGroup := Actions.GiveGroup(5, 22, 140, 30, 6, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 22, 140, 120, 6, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 16, 143, 40, 6, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);
         AIGroup := Actions.GiveGroup(5, 16, 143, 110, 6, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 94, 6);
         AIGroup := Actions.GiveGroup(5, 26, 135, 15, 6, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 95, 58, 6);

         AIGroup := Actions.GiveGroup(6, 22, 30, 140, 0, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 22, 120, 140, 0, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 40, 140, 0, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 57, 95, 0);
         AIGroup := Actions.GiveGroup(6, 16, 110, 140, 0, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);
         AIGroup := Actions.GiveGroup(6, 26, 135, 135, 0, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 94, 95, 0);

         AIGroup := Actions.GiveGroup(7, 22, 10, 30, 2, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 22, 10, 120, 2, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 16, 7, 40, 2, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 58, 2);
         AIGroup := Actions.GiveGroup(7, 16, 7, 110, 2, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
         AIGroup := Actions.GiveGroup(7, 26, 15, 135, 2, 30, 6);
         Actions.GroupOrderWalk(AIGroup, 55, 94, 2);
       end;
  end;
end;


procedure GetRescue(aPlayer: Integer);
var
  aTypes: array[0..4] of Integer;
  Group: Integer;
begin
  for I := 0 to 4 do
  begin
    aTypes[I] := States.KaMRandomI(8) + 15;
    if aTypes[I] = 15 then
      aTypes[I] := 16;
    if aTypes[I] = 19 then
      aTypes[I] := 20;
    if aTypes[I] = 21 then
      aTypes[I] := 22;
    if aTypes[I] = 18 then
      if States.KaMRandom > 0.35 then
        aTypes[I] := 20;
  end;

  for I := 0 to 4 do
  begin
    Group := Actions.GiveGroup(aPlayer, aTypes[I], RescueSquadPositionX[aPlayer][I], RescueSquadPositionY[aPlayer][I], Direction[aPlayer], States.KaMRandomI(4) + 15, RescueSquadFormation[aPlayer][I]);
    Actions.GroupHungerSet(Group, States.UnitMaxHunger);
  end;
end;


procedure OnPlanRoadPlaced(aIndex, aX, aY: Integer);
var
  aPlayer: Integer;
begin
  Actions.PlanRemove(aIndex, aX, aY);
  if Wave >= RESCUE_WAVE then
  begin
    aPlayer := aIndex;
    if (aX = RescueTileX[aPlayer])
    and (aY = RescueTileY[aPlayer])
    and (RescuesDelay[aPlayer] = 0)
    and (RescuesCount[aPlayer] > 0)
    and (States.StatArmyCount(aPlayer) <= RESCUE_ARMY_COUNT)
    and (States.StatUnitTypeCount(aPlayer, 13) <= RESCUE_RECRUITS_COUNT) then
    begin
      GetRescue(aPlayer);
      RescuesDelay[aPlayer] := RESCUE_DELAY;
      RescuesCount[aPlayer] := RescuesCount[aPlayer] - 1;
    end;
  end;
end;


procedure OnPlanFieldPlaced(aIndex, aX, aY: Integer);
begin
  Actions.PlanRemove(aIndex, aX, aY);
end;


procedure OnPlanWinefieldPlaced(aIndex, aX, aY: Integer);
var
  Troops: array of Integer;
begin
  if DEBUG_MODE then
  begin
    Troops := States.PlayerGetAllUnits(aIndex);
    for K := 0 to length(Troops) - 1 do
      Actions.UnitHungerSet(Troops[K], States.UnitMaxHunger);
  end;
  Actions.PlanRemove(aIndex, aX, aY);
end;


procedure CheckRescueDelay;
begin
  for I := 0 to 3 do
  begin
    if RescuesDelay[I] > 0 then
      RescuesDelay[I] := RescuesDelay[I] - 1;
    if RescuesCount[I] = 0 then
      RescuesDelay[I] := 0;
  end;
end;


procedure CheckRescueColor(aPlayer: Integer);
begin
  if (States.StatArmyCount(aPlayer) <= RESCUE_ARMY_COUNT)
  and (States.StatUnitTypeCount(aPlayer, 13) <= RESCUE_RECRUITS_COUNT)
  and (RescuesCount[aPlayer] > 0)
  and (RescuesDelay[aPlayer] = 0) then
    RescueColor[aPlayer] := '00FF00'
  else
    RescueColor[aPlayer] := '0000FF';
end;


procedure OnTick;
begin

  Actions.OverlayTextSetFormatted(-1, DebugHeader + '<$2> ' + IntToStr(Wave) + ' - ' + WaveName + '|<$5>' + '|<$1>', [((WaveTime div 600) mod 60), ((WaveTime div 10) mod 60)]);
  for I := 0 to 3 do
  begin
    if States.PlayerEnabled(I) then
      Actions.OverlayTextAppendFormatted(-1, '|<$0>', [States.PlayerColorText(I), States.PlayerName(I), Scores[I]]);
  end;

  for I := 0 to 3 do
  begin
    if States.PlayerEnabled(I) then
      if Wave >= RESCUE_WAVE then
        Actions.OverlayTextAppendFormatted(I, '<$50>', [RescueColor[I], RescuesCount[I], ((RescuesDelay[I] div 600) mod 60), ((RescuesDelay[I] div 10) mod 60), States.StatArmyCount(I), RescueArmy[I], States.StatUnitTypeCount(I, 13), RescueRecruits[I]]);
  end;

  if (((States.GameTime <= 25200) and (States.GameTime mod 1200 = 0))
  or ((States.GameTime > 25200) and (States.GameTime mod 1800 = 0)))
  and (Wave < MAX_WAVE) then
    GetAttacks;

  if States.GameTime mod 15000 = 0 then
    Actions.UnitHungerSet(General, States.UnitMaxHunger);

  if (Wave >= MAX_WAVE)
  and (States.StatArmyCount(4) + States.StatArmyCount(5) + States.StatArmyCount(6) + States.StatArmyCount(7) = 0) then
    Actions.PlayerWin([0, 1, 2, 3, 8], True);

  if (States.StatArmyCount(8) = 0)
  or (States.StatHouseTypeCount(8, 21) = 0) then
    for I := 0 to 3 do
      if States.PlayerEnabled(I) then
        Actions.PlayerDefeat(I);

  GetTimer;

  if States.GameTime mod 100 = 0 then
    ContinueAttack;

  if (States.GameTime mod 15 = 0)
  and (InRange(Wave, 2, 12)) then
    AttackCenter;

  if (Wave = BONUS_WAVE)
  and not (DEBUG_MODE)
  and not (Check) then
  begin
    CheckBonus;
    Check := True;
  end;

  if (Wave = RESCUE_WAVE)
  and not (bRescueMsg) then
  begin
    for I := 0 to 3 do
      if States.PlayerEnabled(I) then
        Actions.ShowMsgGoTo(I, RescueTileX[I], RescueTileY[I], '<$49>');
    bRescueMsg := True;
  end;

  CheckRescueDelay;

  for I := 0 to 3 do
    if States.PlayerEnabled(I) then
      CheckRescueColor(I);

  if (Wave >= BONUS_WAVE)
  and (DEBUG_MODE) then
    CheckDebugBonus;


  if States.GameTime mod 101 = 0 then
    CheckIdleGroups;

end;