SC_SCROLL_LEFT = 0; //Scroll Left
SC_SCROLL_RIGHT = 1; //Scroll Right
SC_SCROLL_UP = 2; //Scroll Up
SC_SCROLL_DOWN = 3; //Scroll Down

SC_MAP_DRAG_SCROLL = 4; //Map drag scroll

SC_ZOOM_IN = 5; //Zoom In
SC_ZOOM_OUT = 6; //Zoom Out
SC_ZOOM_RESET = 7; //Reset Zoom

SC_CLOSE_MENU = 8; //Close opened menu

SC_PLAN_ROAD = 9; //Plan road
SC_PLAN_FIELD = 10; //Plan field
SC_PLAN_WINE = 11; //Plan wine
SC_ERASE_PLAN = 12; //Erase plan

SC_DEBUG_WINDOW = 13; //Debug window
SC_DEBUG_REVEALMAP = 14; //Debug Menu Reveal Map
SC_DEBUG_VICTORY = 15; //Debug Menu Victory
SC_DEBUG_DEFEAT = 16; //Debug Menu Defeat
SC_DEBUG_ADDSCOUT = 17; //Debug Menu Add Scout

SC_MENU_BUILD = 18; //Build Menu
SC_MENU_RATIO = 19; //Ratio Menu
SC_MENU_STATS = 20; //Stats Menu
SC_MENU_MENU = 21; //Main Menu

SC_ARMY_HALT = 22; //Halt Command
SC_ARMY_SPLIT = 23; //Split up Command
SC_ARMY_LINK = 24; //Linkup Command
SC_ARMY_FOOD = 25; //Food Command
SC_ARMY_STORM = 26; //Storm Command
SC_ARMY_ADD_LINE = 27; //Formation Increase Line Command
SC_ARMY_DEL_LINE = 28; //Formation Shrink Line Command
SC_ARMY_ROTATE_CW = 29; //Turn Right Command
SC_ARMY_ROTATE_CCW = 30; //Turn Left Command

SC_SPEEDUP_1 = 31; //Speed up 1
SC_SPEEDUP_2 = 32; //Speed up 2
SC_SPEEDUP_3 = 33; //Speed up 3
SC_SPEEDUP_4 = 34; //Speed up 4

SC_BEACON = 35; //Beacon
SC_PAUSE = 36; //Pause
SC_SHOW_TEAMS = 37; //Show teams in MP

SC_CENTER_ALERT = 38; //Center to alert
SC_DELETE_MSG = 39; //Delete message
SC_CHAT_MP = 40; //Show the chat

SC_NEXT_BLD_UNIT_SAME_TYPE = 41; //Select next building/unit with same type

SC_SELECT_1 = 42; //Select 1
SC_SELECT_2 = 43; //Select 2
SC_SELECT_3 = 44; //Select 3
SC_SELECT_4 = 45; //Select 4
SC_SELECT_5 = 46; //Select 5
SC_SELECT_6 = 47; //Select 6
SC_SELECT_7 = 48; //Select 7
SC_SELECT_8 = 49; //Select 8
SC_SELECT_9 = 50; //Select 9
SC_SELECT_10 = 51; //Select 10
SC_SELECT_11 = 52; //Select 11
SC_SELECT_12 = 53; //Select 12
SC_SELECT_13 = 54; //Select 13
SC_SELECT_14 = 55; //Select 14
SC_SELECT_15 = 56; //Select 15
SC_SELECT_16 = 57; //Select 16
SC_SELECT_17 = 58; //Select 17
SC_SELECT_18 = 59; //Select 18
SC_SELECT_19 = 60; //Select 19
SC_SELECT_20 = 61; //Select 20

SC_SPECTATE_PLAYER_1 = 62; //Spectate player 1
SC_SPECTATE_PLAYER_2 = 63; //Spectate player 2
SC_SPECTATE_PLAYER_3 = 64; //Spectate player 3
SC_SPECTATE_PLAYER_4 = 65; //Spectate player 4
SC_SPECTATE_PLAYER_5 = 66; //Spectate player 5
SC_SPECTATE_PLAYER_6 = 67; //Spectate player 6
SC_SPECTATE_PLAYER_7 = 68; //Spectate player 7
SC_SPECTATE_PLAYER_8 = 69; //Spectate player 8

SC_MAPEDIT_EXTRA = 70; // MapEdit Extra's menu
SC_MAPEDIT_TERRAIN = 71; // MapEdit Terrain Editing
SC_MAPEDIT_VILLAGE = 72; // MapEdit Village Planning
SC_MAPEDIT_VISUAL = 73; // MapEdit Visual Scripts
SC_MAPEDIT_GLOBAL = 74; // MapEdit Global Scripting
SC_MAPEDIT_MAIN_MANU = 75; // MapEdit Main Menu
SC_MAPEDIT_SUB_MENU_1 = 76; // MapEdit Sub-menu 1
SC_MAPEDIT_SUB_MENU_2 = 77; // MapEdit Sub-menu 2
SC_MAPEDIT_SUB_MENU_3 = 78; // MapEdit Sub-menu 3
SC_MAPEDIT_SUB_MENU_4 = 79; // MapEdit Sub-menu 4
SC_MAPEDIT_SUB_MENU_5 = 80; // MapEdit Sub-menu 5
SC_MAPEDIT_SUB_MENU_6 = 81; // MapEdit Sub-menu 6
SC_MAPEDIT_OBJ_PALETTE = 82; // MapEdit Objects palette
SC_MAPEDIT_UNIV_ERASOR = 83; // MapEdit Universal erasor

