SC_SCROLL_LEFT = 0; //Scroll Left
SC_SCROLL_RIGHT = 1; //Scroll Right
SC_SCROLL_UP = 2; //Scroll Up
SC_SCROLL_DOWN = 3; //Scroll Down

SC_ZOOM_IN = 4; //Zoom In
SC_ZOOM_OUT = 5; //Zoom Out
SC_ZOOM_RESET = 6; //Reset Zoom

SC_CLOSE_MENU = 7; //Close opened menu

SC_PLAN_ROAD = 8; //Plan road
SC_PLAN_FIELD = 9; //Plan field
SC_PLAN_WINE = 10; //Plan wine
SC_ERASE_PLAN = 11; //Erase plan

SC_DEBUG_REVEALMAP = 12; //Debug Menu Reveal Map
SC_DEBUG_VICTORY = 13; //Debug Menu Victory
SC_DEBUG_DEFEAT = 14; //Debug Menu Defeat
SC_DEBUG_ADDSCOUT = 15; //Debug Menu Add Scout

SC_MENU_BUILD = 16; //Build Menu
SC_MENU_RATIO = 17; //Ratio Menu
SC_MENU_STATS = 18; //Stats Menu
SC_MENU_MENU = 19; //Main Menu

SC_ARMY_HALT = 20; //Halt Command
SC_ARMY_SPLIT = 21; //Split up Command
SC_ARMY_LINK = 22; //Linkup Command
SC_ARMY_FOOD = 23; //Food Command
SC_ARMY_STORM = 24; //Storm Command
SC_ARMY_ADD_LINE = 25; //Formation Increase Line Command
SC_ARMY_DEL_LINE = 26; //Formation Shrink Line Command
SC_ARMY_ROTATE_CW = 27; //Turn Right Command
SC_ARMY_ROTATE_CCW = 28; //Turn Left Command

SC_SPEEDUP_1 = 29; //Speed up 1
SC_SPEEDUP_2 = 30; //Speed up 2
SC_SPEEDUP_3 = 31; //Speed up 3
SC_SPEEDUP_4 = 32; //Speed up 4

SC_BEACON = 33; //Beacon
SC_PAUSE = 34; //Pause
SC_SHOW_TEAMS = 35; //Show teams in MP

SC_CENTER_ALERT = 36; //Center to alert
SC_DELETE_MSG = 37; //Delete message
SC_CHAT_MP = 38; //Show the chat

SC_NEXT_BLD_UNIT_SAME_TYPE = 39; //Select next building/unit with same type 

SC_SELECT_1 = 40; //Select 1
SC_SELECT_2 = 41; //Select 2
SC_SELECT_3 = 42; //Select 3
SC_SELECT_4 = 43; //Select 4
SC_SELECT_5 = 44; //Select 5
SC_SELECT_6 = 45; //Select 6
SC_SELECT_7 = 46; //Select 7
SC_SELECT_8 = 47; //Select 8
SC_SELECT_9 = 48; //Select 9
SC_SELECT_10 = 49; //Select 10
SC_SELECT_11 = 50; //Select 11
SC_SELECT_12 = 51; //Select 12
SC_SELECT_13 = 52; //Select 13
SC_SELECT_14 = 53; //Select 14
SC_SELECT_15 = 54; //Select 15
SC_SELECT_16 = 55; //Select 16
SC_SELECT_17 = 56; //Select 17
SC_SELECT_18 = 57; //Select 18
SC_SELECT_19 = 58; //Select 19
SC_SELECT_20 = 59; //Select 20

SC_MAPEDIT_EXTRA = 60; // MapEdit Extra's menu
SC_MAPEDIT_TERRAIN = 61; // MapEdit Terrain Editing
SC_MAPEDIT_VILLAGE = 62; // MapEdit Village Planning
SC_MAPEDIT_VISUAL = 63; // MapEdit Visual Scripts
SC_MAPEDIT_GLOBAL = 64; // MapEdit Global Scripting
SC_MAPEDIT_MAIN_MANU = 65; // MapEdit Main Menu
SC_MAPEDIT_SUB_MENU_1 = 66; // MapEdit Sub-menu 1
SC_MAPEDIT_SUB_MENU_2 = 67; // MapEdit Sub-menu 2
SC_MAPEDIT_SUB_MENU_3 = 68; // MapEdit Sub-menu 3
SC_MAPEDIT_SUB_MENU_4 = 69; // MapEdit Sub-menu 4
SC_MAPEDIT_SUB_MENU_5 = 70; // MapEdit Sub-menu 5
SC_MAPEDIT_SUB_MENU_6 = 71; // MapEdit Sub-menu 6
