SC_SCROLL_LEFT = 0; //Scroll Left
SC_SCROLL_RIGHT = 1; //Scroll Right
SC_SCROLL_UP = 2; //Scroll Up
SC_SCROLL_DOWN = 3; //Scroll Down

SC_MENU_BUILD = 4; //Build Menu
SC_MENU_RATIO = 5; //Ratio Menu
SC_MENU_STATS = 6; //Stats Menu
SC_MENU_MENU = 7; //Main Menu

SC_ARMY_HALT = 8; //Halt Command
SC_ARMY_SPLIT = 9; //Split up Command
SC_ARMY_LINK = 10; //Linkup Command
SC_ARMY_FOOD = 11; //Food Command
SC_ARMY_STORM = 12; //Storm Command
SC_ARMY_ADD_LINE = 13; //Formation Increase Line Command
SC_ARMY_DEL_LINE = 14; //Formation Shrink Line Command
SC_ARMY_ROTATE_CW = 15; //Turn Right Command
SC_ARMY_ROTATE_CCW = 16; //Turn Left Command

SC_SPEEDUP_1 = 17; //Speed up 1
SC_SPEEDUP_2 = 18; //Speed up 2
SC_SPEEDUP_3 = 19; //Speed up 3
SC_SPEEDUP_4 = 20; //Speed up 4

SC_BEACON = 21; //Beacon
SC_PAUSE = 22; //Pause
SC_SHOW_TEAMS = 23; //Show teams in MP
SC_ZOOM_IN = 24; //Zoom In
SC_ZOOM_OUT = 25; //Zoom Out
SC_ZOOM_RESET = 26; //Reset Zoom

SC_SELECT_1 = 27; //Select 1
SC_SELECT_2 = 28; //Select 2
SC_SELECT_3 = 29; //Select 3
SC_SELECT_4 = 30; //Select 4
SC_SELECT_5 = 31; //Select 5
SC_SELECT_6 = 32; //Select 6
SC_SELECT_7 = 33; //Select 7
SC_SELECT_8 = 34; //Select 8
SC_SELECT_9 = 35; //Select 9
SC_SELECT_10 = 36; //Select 10

SC_CENTER_ALERT = 37; //Center to alert
SC_DELETE_MSG = 38; //Delete message
SC_CHAT_MP = 39; //Show the chat

SC_CLOSE_MENU = 40; //Close opened menu

SC_DEBUG_REVEALMAP = 41; //Debug Menu Reveal Map
SC_DEBUG_VICTORY = 42; //Debug Menu Victory
SC_DEBUG_DEFEAT = 43; //Debug Menu Defeat
SC_DEBUG_ADDSCOUT = 44; //Debug Menu Add Scout

SC_MAPEDIT_EXTRA = 45; // MapEdit Extra's menu
SC_MAPEDIT_TERRAIN = 46; // MapEdit Terrain Editing
SC_MAPEDIT_VILLAGE = 47; // MapEdit Village Planning
SC_MAPEDIT_VISUAL = 48; // MapEdit Visual Scripts
SC_MAPEDIT_GLOBAL = 49; // MapEdit Global Scripting
SC_MAPEDIT_MAIN_MANU = 50; // MapEdit Main Menu
SC_MAPEDIT_SUB_MENU_1 = 51; // MapEdit Sub-menu 1
SC_MAPEDIT_SUB_MENU_2 = 52; // MapEdit Sub-menu 2
SC_MAPEDIT_SUB_MENU_3 = 53; // MapEdit Sub-menu 3
SC_MAPEDIT_SUB_MENU_4 = 54; // MapEdit Sub-menu 4
SC_MAPEDIT_SUB_MENU_5 = 55; // MapEdit Sub-menu 5
SC_MAPEDIT_SUB_MENU_6 = 56; // MapEdit Sub-menu 6
