procedure OnTick;
begin
  if States.GameTime = 5 then
    Actions.ShowMsg(0, States.Text(0));
  if States.GameTime = 5 then
    Actions.ShowMsg(1, States.Text(0));

  if States.GameTime = 1000 then
    Actions.ShowMsg(0, States.Text(1));
  if States.GameTime = 1000 then
    Actions.ShowMsg(1, States.Text(1));

  if States.GameTime = 1800 then
    Actions.ShowMsg(0, States.Text(2));
  if States.GameTime = 1800 then
    Actions.ShowMsg(1, States.Text(2));
end;