  procedure OnTick;
    begin
      if States.GameTime = 200 then begin
       Actions.GiveGroup(1, 15, 10, 73, 1, 15, 5);
       Actions.GiveGroup(1, 17, 6, 76, 1, 12, 4);
       Actions.GiveGroup(3, 15, 33, 51, 2, 15, 5);
       Actions.GiveGroup(3, 21, 38, 24, 3, 18, 6);
     end;

      if States.GameTime = 600 then
       Actions.GiveGroup(3, 15, 35, 17, 4, 18, 6);

      if States.GameTime = 650 then
       Actions.GiveGroup(4, 22, 4, 34, 2, 12, 4);

     end;
