procedure OnTick;
var
  I, K: Integer;
  UnitsToFeed: array of Integer;
begin
  if States.GameTime mod 12000 = 0 then
  for I := 3 to 11 do
  begin
    UnitsToFeed := States.PlayerGetAllUnits(I);
    for K := 0 to Length(UnitsToFeed) - 1 do
    begin
      Actions.UnitHungerSet(UnitsToFeed[K], 45*60*10);
    end;
  end; 
end;


{procedure OnHouseBuilt(aHouseID: Integer);
begin
  Actions.HouseRepairEnable(aHouseID, True);
end;}
