del "MapsMP\Lake Wololo\Lake Wololo - Copy.map"

rd /s /q "MapsMP\Cross_update"
rd /s /q "MapsMP\Forest Fight The Clearing"
rd /s /q "MapsMP\Forest Fight The Raid"
rd /s /q "MapsMP\Forest Fight The Siege"
rd /s /q "MapsMP\Ruined City"
rd /s /q "MapsMP\Stranded"

rd /s /q "Resource\"
rd /s /q "Sprites\"
rd /s /q "data\misc\"
rd /s /q "data\gfx\res\"
rd /s /q "data\mission\"

del "Sounds\UI\Error001.wav"
del "Sounds\UI\Error002.wav"
del "Sounds\Chat\ChatArrive_old.wav"
del "Campaigns\The Shattered Kingdom\TSK20\TSK20.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK19\TSK19.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK18\TSK18.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK14\TSK14.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK12\TSK12.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK11\TSK11.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK10\TSK10.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK09\TSK09.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK08\TSK08.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK07\TSK07.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK05\TSK05.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK04\TSK04.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK02\TSK02.swe.libx"
del "Campaigns\The Shattered Kingdom\TSK01\TSK01.swe.libx"
del "data\Sprites\RemakeMenu.rxx"
del "data\Sprites\RemakeGame.rxx"
del "data\sfx\speech.spa\swordman\attack4,.wav"
del "data\sfx\speech.spa\swordman\attack3,.wav"
del "data\sfx\speech.spa\knights\-send4.wav"
del "data\sfx\speech.hun\barbarian\storm3.wav"
del "bass.dll"

rd /s /q "MapsMP\Time to Die II - Gorge"
rd /s /q "MapsMP\Time to Die I - Swamp"
rd /s /q "MapsMP\The Valley of Dangers"
rd /s /q "MapsMP\The Kings Favorite"
rd /s /q "MapsMP\Heroes of Might & Axe II"
rd /s /q "MapsMP\Heroes of Might & Axe I"
rd /s /q "MapsMP\Dark Rock 4P"
rd /s /q "MapsMP\Dark Rock 6P"
rd /s /q "MapsMP\Center Castle 4P"
rd /s /q "MapsMP\Center Castle 8P"

rd /s /q "MapsMP\TPR 5"
rd /s /q "MapsMP\TPR 6"
rd /s /q "MapsMP\TPR 7"
rd /s /q "MapsMP\TPR 8"
rd /s /q "MapsMP\TPR 9"
rd /s /q "MapsMP\TSK 7"
rd /s /q "MapsMP\TSK 8"

rd /s /q "MapsMP\Clash"
rd /s /q "MapsMP\Lost Lands"
rd /s /q "Maps\AI Builders"

del "data\gfx\fonts\antiqua.LITH.fnt"
del "data\gfx\fonts\game.LITH.fnt"
del "data\gfx\fonts\grey.LITH.fnt"
del "data\gfx\fonts\metal.LITH.fnt"
del "data\gfx\fonts\mini.LITH.fnt"
del "data\gfx\fonts\outline.LITH.fnt"

del "Campaigns\The Peasants Rebellion\TPR01\TPR01.evt"
del "Campaigns\The Peasants Rebellion\TPR03\TPR03.evt"
del "Campaigns\The Peasants Rebellion\TPR04\TPR04.evt"
del "Campaigns\The Peasants Rebellion\TPR06\TPR06.evt"
del "Campaigns\The Peasants Rebellion\TPR07\TPR07.evt"
del "Campaigns\The Peasants Rebellion\TPR09\TPR09.evt"
del "Campaigns\The Peasants Rebellion\TPR10\TPR10.evt"
del "Campaigns\The Peasants Rebellion\TPR12\TPR12.evt"
del "Campaigns\The Peasants Rebellion\TPR13\TPR13.evt"
del "Campaigns\The Peasants Rebellion\TPR14\TPR14.evt"
del "Campaigns\The Shattered Kingdom\TSK01\TSK01.evt"
del "Campaigns\The Shattered Kingdom\TSK02\TSK02.evt"
del "Campaigns\The Shattered Kingdom\TSK04\TSK04.evt"
del "Campaigns\The Shattered Kingdom\TSK05\TSK05.evt"
del "Campaigns\The Shattered Kingdom\TSK07\TSK07.evt"
del "Campaigns\The Shattered Kingdom\TSK08\TSK08.evt"
del "Campaigns\The Shattered Kingdom\TSK09\TSK09.evt"
del "Campaigns\The Shattered Kingdom\TSK10\TSK10.evt"
del "Campaigns\The Shattered Kingdom\TSK11\TSK11.evt"
del "Campaigns\The Shattered Kingdom\TSK12\TSK12.evt"
del "Campaigns\The Shattered Kingdom\TSK14\TSK14.evt"
del "Campaigns\The Shattered Kingdom\TSK18\TSK18.evt"
del "Campaigns\The Shattered Kingdom\TSK19\TSK19.evt"
del "Campaigns\The Shattered Kingdom\TSK20\TSK20.evt"
del "Tutorials\Battle Tutorial\Battle Tutorial.evt"
del "Tutorials\Town Tutorial\Town Tutorial.evt"

del "data\gfx\fonts\antiqua.1250.fnt"
del "data\gfx\fonts\antiqua.1251.fnt"
del "data\gfx\fonts\antiqua.1252.fnt"
del "data\gfx\fonts\antiqua.1257.fnt"
del "data\gfx\fonts\antiqua.TURK.fnt"
del "data\gfx\fonts\briefing.1250.fnt"
del "data\gfx\fonts\briefing.1251.fnt"
del "data\gfx\fonts\briefing.1252.fnt"
del "data\gfx\fonts\game.1250.fnt"
del "data\gfx\fonts\game.1251.fnt"
del "data\gfx\fonts\game.1252.fnt"
del "data\gfx\fonts\game.1257.fnt"
del "data\gfx\fonts\game.TURK.fnt"
del "data\gfx\fonts\grey.1250.fnt"
del "data\gfx\fonts\grey.1251.fnt"
del "data\gfx\fonts\grey.1252.fnt"
del "data\gfx\fonts\grey.1257.fnt"
del "data\gfx\fonts\grey.TURK.fnt"
del "data\gfx\fonts\mainb.1250.fnt"
del "data\gfx\fonts\mainb.1251.fnt"
del "data\gfx\fonts\mainb.1252.fnt"
del "data\gfx\fonts\mainmapgold.1250.fnt"
del "data\gfx\fonts\mainmapgold.1251.fnt"
del "data\gfx\fonts\mainmapgold.1252.fnt"
del "data\gfx\fonts\metal.1250.fnt"
del "data\gfx\fonts\metal.1251.fnt"
del "data\gfx\fonts\metal.1252.fnt"
del "data\gfx\fonts\metal.1257.fnt"
del "data\gfx\fonts\metal.TURK.fnt"
del "data\gfx\fonts\mini.1250.fnt"
del "data\gfx\fonts\mini.1251.fnt"
del "data\gfx\fonts\mini.1252.fnt"
del "data\gfx\fonts\mini.1257.fnt"
del "data\gfx\fonts\mini.TURK.fnt"
del "data\gfx\fonts\outline.1250.fnt"
del "data\gfx\fonts\outline.1251.fnt"
del "data\gfx\fonts\outline.1252.fnt"
del "data\gfx\fonts\outline.1257.fnt"
del "data\gfx\fonts\outline.TURK.fnt"
del "data\gfx\fonts\won.1250.fnt"
del "data\gfx\fonts\won.1251.fnt"
del "data\gfx\fonts\won.1252.fnt"
del "data\sfx\speech.eng\rogue\attack0.snd"
del "data\sfx\speech.eng\rogue\attack1.snd"
del "data\sfx\speech.eng\rogue\attack2.snd"
del "data\sfx\speech.eng\rogue\battle0.snd"
del "data\sfx\speech.eng\rogue\battle1.snd"
del "data\sfx\speech.eng\rogue\battle2.snd"
del "data\sfx\speech.eng\rogue\death0.snd"
del "data\sfx\speech.eng\rogue\death1.snd"
del "data\sfx\speech.eng\rogue\death2.snd"
del "data\sfx\speech.eng\rogue\eat0.snd"
del "data\sfx\speech.eng\rogue\eat1.snd"
del "data\sfx\speech.eng\rogue\eat2.snd"
del "data\sfx\speech.eng\rogue\format0.snd"
del "data\sfx\speech.eng\rogue\format1.snd"
del "data\sfx\speech.eng\rogue\format2.snd"
del "data\sfx\speech.eng\rogue\halt0.snd"
del "data\sfx\speech.eng\rogue\halt1.snd"
del "data\sfx\speech.eng\rogue\halt2.snd"
del "data\sfx\speech.eng\rogue\halve0.snd"
del "data\sfx\speech.eng\rogue\halve1.snd"
del "data\sfx\speech.eng\rogue\halve2.snd"
del "data\sfx\speech.eng\rogue\halve3.snd"
del "data\sfx\speech.eng\rogue\join0.snd"
del "data\sfx\speech.eng\rogue\join1.snd"
del "data\sfx\speech.eng\rogue\join2.snd"
del "data\sfx\speech.eng\rogue\left0.snd"
del "data\sfx\speech.eng\rogue\left1.snd"
del "data\sfx\speech.eng\rogue\left2.snd"
del "data\sfx\speech.eng\rogue\right0.snd"
del "data\sfx\speech.eng\rogue\right1.snd"
del "data\sfx\speech.eng\rogue\right2.snd"
del "data\sfx\speech.eng\rogue\select0.snd"
del "data\sfx\speech.eng\rogue\select1.snd"
del "data\sfx\speech.eng\rogue\select2.snd"
del "data\sfx\speech.eng\rogue\select3.snd"
del "data\sfx\speech.eng\rogue\select4.snd"
del "data\sfx\speech.eng\rogue\send0.snd"
del "data\sfx\speech.eng\rogue\send1.snd"
del "data\sfx\speech.eng\rogue\send2.snd"
del "data\sfx\speech.eng\rogue\send3.snd"
del "data\sfx\speech.eng\rogue\send4.snd"
del "data\Sprites\GUIMainH.rxx"
del "Maps\AcrossDesert\AcrossDesert.dat"
del "Maps\AcrossDesert\AcrossDesert.map"
del "Maps\AcrossDesert\AcrossDesert.txt"
del "Maps\AcrossDesert 8P\AcrossDesert 8P.dat"
del "Maps\AcrossDesert 8P\AcrossDesert 8P.map"
del "Maps\Alcatraz\Alcatraz.dat"
del "Maps\Alcatraz\Alcatraz.map"
del "Maps\Alcatraz\Alcatraz.txt"
del "Maps\Revenge\Revenge.dat"
del "Maps\Revenge\Revenge.map"
del "Maps\Revenge\Revenge.txt"
del "Maps\Stuck in the Middle\Stuck in the Middle.dat"
del "Maps\Stuck in the Middle\Stuck in the Middle.map"
del "Maps\Stuck in the Middle\Stuck in the Middle.txt"
del "Maps\The Crusade\The Crusade.dat"
del "Maps\The Crusade\The Crusade.map"
del "Maps\The Crusade\The Crusade.txt"

rd /s /q "Maps\AcrossDesert"
rd /s /q "Maps\AcrossDesert 8P"
rd /s /q "Maps\Alcatraz"
rd /s /q "Maps\Revenge"
rd /s /q "Maps\Stuck in the Middle"
rd /s /q "Maps\The Crusade"

del PostInstallClean.bat